# admin user
admin:
  id: 'admin'
  password: 'admin'

spring:
  profiles:
    active: test
  datasource:
    url: 'jdbc:tc:postgresql:11-alpine:///databasename'
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        order_inserts: true
        ddl-auto: create
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 50

