# admin user
admin:
  id: 'admin'
  password: 'admin'

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/test'
    hikari:
      username: 'test'
      password: 'test'
#      maximum-pool-size: 100
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        order_inserts: true
        ddl-auto: create
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 50
