token:
  secret: '21edc783bca7b12425ccd76e9bb135d868b478286e1ea49965c9ae7138345fb3a5dc90cebae25c76d246529664bd223c81842fa37387b0d444986d30828288bb'
  expiration_time: 86400000 # 1 day
  refresh_expiration_time: 604800000 # 7 days

benchmark:
  version: '1.0.0'
  name: 'benchmark'
  description: 'Benchmark application'
  contacts: Gyumin Hwangbo;ghkdqhrbals@gmail.com,JeongGi Lee;apple4rhk@naver.com

# admin user
admin:
  id: 'admin'
  password: 'admin'

spring:
  profiles:
    active: production
  datasource:
    url: 'jdbc:postgresql://localhost:5433/test'
    hikari:
      username: 'test'
      password: 'test'
  #      maximum-pool-size: 100
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        order_inserts: true
        ddl-auto: update
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 50
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'apple4rhk'
    password: 'rdndiwbefqkbvnau'
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000
        smtp.starttls.enable: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org:
      springframework:
        security: INFO

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 엔드포인트를 노출합니다. 필요에 따라 특정 엔드포인트만 선택할 수도 있습니다.
  endpoint:
    health:
      show-details: always  # Health 엔드포인트에서 상세 정보를 항상 표시합니다.
  health:
    groups:
      readiness:
        include: "*"  # 모든 상태를 readiness 그룹에 포함합니다.
      liveness:
        include: "*"  # 모든 상태를 liveness 그룹에 포함합니다.
  info:
    app:
      name: "BM-Controller"  # 애플리케이션 이름을 설정합니다.
      version: "1.0.0"  # 애플리케이션 버전을 설정합니다.
    contact:
      name: "gyumin hwangbo"  # 연락처 이름을 설정합니다.
      email: "ghkdqhrbals@gmail.com"  # 이메일 주소를 설정합니다.