token:
  secret: '21edc783bca7b12425ccd76e9bb135d868b478286e1ea49965c9ae7138345fb3a5dc90cebae25c76d246529664bd223c81842fa37387b0d444986d30828288bb'
  expiration_time: 86400000 # 1 day
  refresh_expiration_time: 604800000 # 7 days

benchmark:
  version: '1.0.0'
  name: 'benchmark'
  description: 'Benchmark application'
  contacts: Gyumin Hwangbo;ghkdqhrbals@gmail.com,JeongGi Lee;apple4rhk@naver.com



# admin user
admin:
  id: 'admin'
  password: 'admin'

spring:
  profiles:
    active: production
  datasource:
    url: 'jdbc:postgresql://localhost:5433/test'
    hikari:
      username: 'test'
      password: 'test'
  #      maximum-pool-size: 100
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        order_inserts: true
        ddl-auto: create
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 50

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    org:
      springframework:
        security: DEBUG