apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: agent-statefulset
spec:
  replicas: 3
  serviceName: agent-service
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
        - name: bm-agent
          imagePullPolicy: Always
          image: ghkdqhrbals/bm-agent:latest
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: eureka_client_serviceUrl_defaultZone
              value: "http://eureka-service:8761/eureka/"