apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginx
  name: mynginx
spec:
  containers:
    - image: nginx:1.16
      name: mynginx
      resources: {}
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: mynginx