apiVersion: v1
kind: Service
metadata:
  labels:
    app: controller-service
  name: controller-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: websocket
      protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP # Expose the service with a NodePort
  selector:
    app: controller-service