apiVersion: v1
kind: Service
metadata:
  labels:
    app: controller-service
  name: controller-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 # Specify the NodePort value
  type: NodePort # Expose the service with a NodePort
  selector:
    app: controller-service